<?php
		include("../../datos/datos.php");
		if (empty($resultado)){
		$resultado="";
		}
		$resultado.="<form id=\"formulario\">";
		$resultado.="<div id=\"transparencia\">";
		$resultado.="<div id=\"transparenciaMensaje\">aaaaaaaaaaaa</div>";
		$resultado.="</div>";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td width=\"31\" class=\"titulo_form\"><img src=\"../../Imagenes/establecimientos.png\" width=\"27\" height=\"27\"></td>";
		$resultado.="<td width=\"613\" class=\"titulo_form\"> Ficha de Establecimientos </td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td class=\"head\">Nombre</td>";
		$resultado.="<td class=\"formulario\"><input name=\"nombre\" type=\"text\" class=\"textbox\" id=\"nombre\" size=\"70\" ></td>";
		$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Nombre')\"></td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td class=\"head\">Telefono:</td>";
		$resultado.="<td class=\"formulario\"><input name=\"telefono\" type=\"text\" class=\"textbox\" id=\"telefono\" ></td>";
		$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Telefono')\"></td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td colspan=\"2\" class=\"head\"><div align=\"center\">Direcci&oacute;n</div></td>";
		$resultado.="</tr>";
		$resultado.="<tr>";
		$resultado.="<td class=\"formulario\"><textarea name=\"direccion\" class=\"textbox\" id=\"direccion\" ></textarea></td>";
		$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Direccion')\"></td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td class=\"head\">Estado:</td>";
		$resultado.="<td class=\"formulario\"><select name=\"estado\" class=\"textbox\" id=\"estado\" onchange=\"verMunicipios()\" >";
		$resultado.="<option value=\"xx\">Seleccione un Estado</option>";
		$estados=Estados();
		$resultado.="$estados";
		$resultado.="</select></td>";
		$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Estado')\"></td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="<div id=\"muni\">";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td class=\"head\">Municipio:</td>";
		$resultado.="<td class=\"formulario\"><select name=\"municipio\"  class=\"textbox\" id=\"municipio\" >";
		$resultado.="</select></td>";
		$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Municipio')\"></td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="</div>";
		$resultado.="<div id=\"parr\">";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td class=\"head\">Parroquia:</td>";
		$resultado.="<td class=\"formulario\"><select name=\"parroquia\"  class=\"textbox\" id=\"parroquia\" >";
		$resultado.="</select></td>";
		$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Parroquia')\"></td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="</div>";
		$resultado.="<div id=\"sect\">";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td class=\"head\">Sector:</td>";
		$resultado.="<td class=\"formulario\"><select name=\"sector\"  class=\"textbox\" id=\"sector\" >";
		$resultado.="</select></td>";
		$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Sector')\"></td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="</div>";
		$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
		$resultado.="<tr>";
		$resultado.="<td class=\"formulario\"><input type=\"button\" class=\"button\" name=\"Submit\" value=\"Guardar\" onClick=\"guardarEstablecimiento()\">";
		$resultado.="<input type=\"button\" class=\"button\" name=\"Submit2\" value=\"Consultar\" onclick=\"consulta()\"></td>";
		$resultado.="</tr>";
		$resultado.="</table>";
		$resultado.="</form>";
	echo $resultado;
?>