<?php
	$id="".$_POST['id']."";
	include '../../datos/datos.php';
	if (empty($resultado)){
	$resultado="";
	}
	$datos=Buscar_establecimiento($id);
	$id=$datos[0];
	$nombre=$datos[1];
	$telefono=$datos[2];
	$direccion=$datos[3];
	$ubicacion=$datos[4];
	$resultado.="<form id=\"formulario\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td width=\"31\" class=\"titulo_form\"><img src=\"../../Imagenes/establecimientos.png\" width=\"27\" height=\"27\"></td>";
	$resultado.="<td width=\"613\" class=\"titulo_form\"> Ficha de Establecimientos </td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Nombre</td>";
	$resultado.="<td class=\"formulario\"><input type=\"hidden\" id=\"idestab\" value=\"$id\"><input name=\"nombre\" type=\"text\" id=\"nombre\" value=\"$nombre\" size=\"70\" class=\"textbox\" disabled></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Nombre')\" ></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Telefono:</td>";
	$resultado.="<td class=\"formulario\"><input type=\"text\" name=\"telefono\" id=\"telefono\" value=\"$telefono\" class=\"textbox\" disabled></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'telefono')\" ></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td colspan=\"2\" class=\"head\"><div align=\"center\">Direcci&oacute;n</div></td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\"><textarea name=\"direccion\" id=\"direccion\" class=\"textbox\" disabled>$direccion</textarea></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Direccion')\" ></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Estado:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"estado\" id=\"estado\" onchange=\"verMunicipios()\" class=\"textbox\" disabled>";
	$resultado.="<option value=\"xx\">Seleccione un Estado</option>";
	$estados=Estados();
	$resultado.="$estados";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Estado')\" ></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<div id=\"muni\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Municipio:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"municipio\" id=\"municipio\" disabled class=\"textbox\" disabled>";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Municipio')\" ></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<div id=\"parr\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Parroquia:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"parroquia\" id=\"parroquia\" disabled class=\"textbox\" disabled>";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Parroquia')\" ></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<div id=\"sect\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Sector:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"sector\" id=\"sector\" disabled class=\"textbox\" disabled>";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Sector')\" ></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\"><input type=\"button\" class=\"button\" name=\"Submit\" value=\"Editar\" onClick=\"editEstablecimiento()\">";
	$resultado.="<input type=\"button\" class=\"button\" name=\"Submit2\" value=\"Consultar\" onclick=\"consulta()\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</form>";
	echo $resultado;
?>