<?php
	$id="".$_POST['id']."";
	include '../../datos/datos.php';
	$datos=Buscar_usuarios($id);
	$id=$datos[0];
	$nombre=$datos[1];
	$login=$datos[2];
	$hnivel=$datos[3];
	$nivel=$datos[4];
	if (empty($resultado)){
	$resultado="";
	}
	$resultado.="<form id=\"formulario\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td width=\"39\" class=\"titulo_form\"><img src=\"../../Imagenes/ubicacion.gif\" width=\"39\" height=\"30\"></td>";
	$resultado.="<td width=\"605\" class=\"titulo_form\">Ficha Ubicacion Geogr&aacute;fica </td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Nombre del Sector: </td>";
	$resultado.="<td class=\"formulario\"><input name=\"nombre\" type=\"text\" id=\"nombre\" size=\"70\" ></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" onmouseover=\"muestraAyuda(event, 'Nombre')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Nombre del Estado: </td>";
	$resultado.="<td class=\"formulario\"><select name=\"estado\" id=\"estado\" >";
	$resultado.=Estados();
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" onmouseover=\"muestraAyuda(event, 'Estado')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<div id=\"muni\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Nombre del Municipio: </td>";
	$resultado.="<td class=\"formulario\"><select name=\"municipio\" id=\"municipio\" >";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" onmouseover=\"muestraAyuda(event, 'Municipio')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<div id=\"parr\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Nombre de la Parroquia: </td>";
	$resultado.="<td class=\"formulario\"><select name=\"parroquia\" id=\"parroquia\" >";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" onmouseover=\"muestraAyuda(event, 'Parroquia')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\"><div align=\"center\">";
	$resultado.="<td class=\"formulario\"><input type=\"button\" name=\"Submit\" value=\"Editar\" onClick=\"editUbicacion()\">";
	$resultado.="<input type=\"button\" name=\"Submit2\" value=\"Consultar\" onclick=\"consulta()\"></td>";
	$resultado.="</div></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<p>&nbsp;</p>";
	$resultado.="</form>";	
	echo $resultado;
?>