<?php
	$hpaciente="".$_POST['hpaciente']."";
	$tensarte = "".$_POST["tensarte"]."";
	$freqcard = "".$_POST["freqcard"]."";
	$freqresp = "".$_POST["freqresp"]."";
	$peso = "".$_POST["peso"]."";
	$talla = "".$_POST["talla"]."";
	$aspecto = "".$_POST["aspecto"]."";
	$hecg = "".$_POST["hecg"]."";
	if (empty($resultado)){
	$resultado="";
	}
	$resultado.="<table cellspacing=\"0\" width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\" width=\"43\"><img src=\"../cardiologico/Imagenes/examen.png\" width=\"33\" height=\"32\"></td>";
	$resultado.="<td class=\"formulario\" width=\"601\" class=\"titulo_form\">FICHA EXAMEN FISICO </td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table cellspacing=\"0\" width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\">Tensi&oacute;n Arterial: </td>";
	$resultado.="<td  class=\"formulario\"><input name=\"tensarte\" type=\"text\" class=\"textbox\" id=\"tensarte\" size=\"10\" value=\"$tensarte\">";
	$resultado.="<input type=\"hidden\" id=\"hpaciente\" name=\"hpaciente\" value=\"$hpaciente\"></td>";
	$resultado.="<td  class=\"formulario\"><img src=\"../cardiologico/Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="<td class=\"formulario\">Frecuencia Cardiaca: </td>";
	$resultado.="<td  class=\"formulario\"><input name=\"freqcard\" type=\"text\" class=\"textbox\" id=\"freqcard\" size=\"10\" value=\"$freqcard\"></td>";
	$resultado.="<td  class=\"formulario\"><img src=\"../cardiologico/Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table cellspacing=\"0\" width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\">Frecuencia Respiratoria: </td>";
	$resultado.="<td class=\"formulario\"><input name=\"freqresp\" type=\"text\" class=\"textbox\" id=\"freqresp\" size=\"10\" value=\"$freqresp\"></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../cardiologico/Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="<td class=\"formulario\">Peso:</td>";
	$resultado.="<td class=\"formulario\"><input name=\"peso\" type=\"text\" class=\"textbox\" id=\"peso\" size=\"10\" value=\"$peso\"></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../cardiologico/Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="<td class=\"formulario\">Talla:</td>";
	$resultado.="<td class=\"formulario\"><input name=\"talla\" type=\"text\" class=\"textbox\" id=\"talla\" size=\"10\" value=\"$talla\"></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../cardiologico/Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table cellspacing=\"0\" width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\" colspan=\"2\"><div align=\"center\">Aspecto General del Paciente</div></td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\"><textarea name=\"aspecto\" class=\"textbox\" id=\"aspecto\" >$aspecto</textarea></td>";
	$resultado.="<td  class=\"formulario\"><img src=\"../cardiologico/Imagenes/info.gif\" width=\"16\" height=\"16\"> </td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table cellspacing=\"0\" width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\">ECG: </td>";
	$resultado.="<td class=\"formulario\"><input name=\"hecg\" type=\"hidden\" id=\"hecg\"  value=\"0\"><input name=\"arhecg\" type=\"file\" class=\"textbox\" id=\"arhecg\" size=\"50\">";
	$resultado.="<td class=\"formulario\"><img src=\"../cardiologico/Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table cellspacing=\"0\" width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\"><input type=\"submit\" class=\"button\" name=\"Submit\" value=\"Enviar\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	echo $resultado;
?>