<?php
	$cedula="".$_POST['cedula']."";
	$nombre="".$_POST['nombre']."";
	$edad="".$_POST['edad']."";
	$sexo="".$_POST['sexo']."";
	$telefono="".$_POST['telefono']."";
	$correo="".$_POST['correo']."";
	$direccion="".$_POST['direccion']."";
	$establecimiento="".$_POST['establecimiento']."";
	$sector="".$_POST['sector']."";
	$direccionest="".$_POST['direccionest']."";
	$telefonoest="".$_POST['telefonoest']."";
	$sectorest="".$_POST['sectorest']."";	
	$estatus=0;
	$loggin="".$_POST['loggin']."";
	$password="".$_POST['password']."";	
	include("../cardiologico/datos/datos.php");
	insertRegistrados($nombre,$cedula,$establecimiento,$edad,$sexo,$direccion,$telefono,$correo,$sector,$estatus,$loggin,$password,$direccionest,$telefonoest,$sectorest);
	include ("insert.php");
?>