<?php
	if (empty($resultado)){
		$resultado="";
	}
	if (empty($cedula)){
		$cedula="";
	}
	if (empty($nombre)){
		$nombre="";
	}
	if (empty($edad)){
		$edad="";
	}
	if (empty($sexo)){
		$sexo="";
	}
	if (empty($telefono)){
		$telefono="";
	}
	if (empty($correo)){
		$correo="";
	}
	if (empty($correo)){
		$correo="";
	}
	if (empty($loggin)){
		$loggin="";
	}
	if (empty($password)){
		$password="";
	}	
	include("../cardiologico/datos/datos.php");
	$resultado.="<form id=\"formulario\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td width=\"60\"  class=\"formulario\"><img src=\"../../Imagenes/fmedicos.png\" width=\"30\" height=\"30\"></td>";
	$resultado.="<td width=\"584\"  class=\"formulario\">Ficha Registro de Usuarios</td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\">C&eacute;dula</td>";
	$resultado.="<td class=\"formulario\"><input name=\"cedula\" type=\"text\" class=\"textbox\" id=\"cedula\" size=\"20\" value=\"$cedula\" ></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Cedula')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Nombre:</td>";
	$resultado.="<td class=\"formulario\"><input name=\"nombre\" type=\"text\" class=\"textbox\" id=\"nombre\" size=\"50\" value=\"$nombre\"  ></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Nombre')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td width=\"77\"  class=\"formulario\">Edad:</td>";
	$resultado.="<td width=\"248\" class=\"formulario\"><input name=\"edad\" type=\"text\" class=\"textbox\" id=\"edad\" size=\"5\"  value=\"$edad\" ></td>";
	$resultado.="<td width=\"67\" class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Edad')\"></td>";
	$resultado.="<td width=\"72\"  class=\"formulario\">Sexo:</td>";
	$resultado.="<td width=\"98\"  class=\"formulario\"><select name=\"sexo\" class=\"textbox\" id=\"sexo\" >";
	$resultado.="<option selected value=\"$sexo\"></option><option value=\"M\">M</option>";
	$resultado.="<option value=\"F\">F</option>";
	$resultado.="</select></td>";
	$resultado.="<td width=\"58\" class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Sexo')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Tel&eacute;fono:</td>";
	$resultado.="<td class=\"formulario\"><input name=\"telefono\" type=\"text\" class=\"textbox\" id=\"telefono\"  value=\"$telefono\" ></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Telefono')\"></td>";
	$resultado.="<td  class=\"formulario\">Correo Electr&oacute;nico </td>";
	$resultado.="<td class=\"formulario\"><input name=\"correo\" type=\"text\" class=\"textbox\" id=\"correo\"  value=\"$correo\" ></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Correo')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td colspan=\"2\"  class=\"formulario\"><div align=\"center\">Direcci&oacute;n</div></td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\"><textarea name=\"direccion\" class=\"textbox\" id=\"direccion\" ></textarea></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Direccion')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Estado:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"estado\" class=\"textbox\" id=\"estado\" onchange=\"verMunicipios()\" >";
	$resultado.="<option value=\"xx\">Seleccione un Estado</option>";
	$estados=Estados();
	$resultado.="$estados";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Estado')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<div id=\"muni\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Municipio:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"municipio\"  class=\"textbox\" id=\"municipio\">";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Municipio')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<div id=\"parr\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Parroquia:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"parroquia\"  class=\"textbox\" id=\"parroquia\">";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Parroquia')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<div id=\"sect\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Sector:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"sector\"  class=\"textbox\" id=\"sector\">";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Sector')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Establecimiento al que esta adscrito:";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<input name=\"establecimiento\" type=\"text\" class=\"textbox\" id=\"establecimiento\" size=\"70\" >";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Nombre')\">";
	$resultado.="</td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Telefono:";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<input name=\"telefonoest\" type=\"text\" class=\"textbox\" id=\"telefonoest\" >";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Telefono')\">";
	$resultado.="</td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td colspan=\"2\"  class=\"formulario\">";
	$resultado.="<div align=\"center\">Direcci&oacute;n";
	$resultado.="</div>";
	$resultado.="</td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<textarea name=\"direccionest\" class=\"textbox\" id=\"direccionest\" >";
	$resultado.="</textarea>";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Direccion')\">";
	$resultado.="</td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Estado:";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<select name=\"estadoest\" class=\"textbox\" id=\"estadoest\" onchange=\"verMunicipiosest()\" >";
	$resultado.="<option value=\"xx\">Seleccione un Estado";
	$resultado.="</option>";
	$estadosest=Estados();
	$resultado.="$estadosest";
	$resultado.="</select>";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Estado')\">";
	$resultado.="</td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<div id=\"muniest\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Municipio:</td>";
	$resultado.="<td class=\"formulario\"><select name=\"municipioest\"  class=\"textbox\" id=\"municipioest\" >";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Municipio')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<div id=\"parrest\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Parroquia:";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\"><select name=\"parroquiaest\"  class=\"textbox\" id=\"parroquiaest\" >";
	$resultado.="</select></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Parroquia')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</div>";
	$resultado.="<div id=\"sectest\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Sector:";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<select name=\"sectorest\"  class=\"textbox\" id=\"sectorest\" >";
	$resultado.="</select>";
	$resultado.="</td>";
	$resultado.="<td class=\"formulario\">";
	$resultado.="<img src=\"../../Imagenes/info.gif\"  width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Sector')\">";
	$resultado.="</td>";
	$resultado.="</tr>";
	$resultado.="</table></div>";		
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Nombre de Usuario:</td>";
	$resultado.="<td class=\"formulario\"><div id=\"logg\"><input name=\"loggin\" type=\"text\" class=\"textbox\" id=\"loggin\" onChange=\"verificarloggin();\" value=\"$loggin\" ></div></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Loggin')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<div id=\"pass\">";
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Contraseña; </td>";
	$resultado.="<td class=\"formulario\"><input name=\"password\" type=\"password\" class=\"textbox\" id=\"password\" value=\"$password\" ></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Password')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";	
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td  class=\"formulario\">Repetir Contraseña; </td>";
	$resultado.="<td class=\"formulario\"><input name=\"password2\" type=\"password\" class=\"textbox\" id=\"password2\" onChange=\"verificarpassword();\"  value=\"$password\" ></td>";
	$resultado.="<td class=\"formulario\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Password')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";	
	$resultado.="</div>";	
	$resultado.="<table width=\"660\" border=\"1\" cellspacing=\"0\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"formulario\"><input type=\"button\" name=\"Submit\" class=\"button\" value=\"Guardar\" onClick=\"guardarRegistro()\">";
	$resultado.="</td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="</form>";
	echo $resultado;
?>