<?php
	$hpaciente="".$_POST['hpaciente']."";
	$tensarte = "".$_POST["tensarte"]."";
	$freqcard = "".$_POST["freqcard"]."";
	$freqresp = "".$_POST["freqresp"]."";
	$peso = "".$_POST["peso"]."";
	$talla = "".$_POST["talla"]."";
	$aspecto = "".$_POST["aspecto"]."";
	$hrxtorax = "".$_POST["hrxtorax"]."";
	$hecg = "".$_POST["hecg"]."";
	if (empty($resultado)){
	$resultado="";
	}
	$resultado.="<table width=\"660\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td width=\"43\"><img src=\"../../Imagenes/examen.png\" width=\"33\" height=\"32\"></td>";
	$resultado.="<td width=\"601\" class=\"titulo_form\">FICHA EXAMEN FISICO </td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Tensi&oacute;n Arterial: </td>";
	$resultado.="<td><input name=\"tensarte\" type=\"text\" class=\"textbox\" id=\"tensarte\" size=\"10\" value=\"$tensarte\">";
	$resultado.="<input type=\"hidden\" id=\"hpaciente\" name=\"hpaciente\" value=\"$hpaciente\"></td>";
	$resultado.="<td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="<td class=\"head\">Frecuencia Cardiaca: </td>";
	$resultado.="<td><input name=\"freqcard\" type=\"text\" class=\"textbox\" id=\"freqcard\" size=\"10\" value=\"$freqcard\"></td>";
	$resultado.="<td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Frecuencia Respiratoria: </td>";
	$resultado.="<td><input name=\"freqresp\" type=\"text\" class=\"textbox\" id=\"freqresp\" size=\"10\" value=\"$freqresp\"></td>";
	$resultado.="<td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="<td class=\"head\">Peso:</td>";
	$resultado.="<td><input name=\"peso\" type=\"text\" class=\"textbox\" id=\"peso\" size=\"10\" value=\"$peso\"></td>";
	$resultado.="<td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="<td class=\"head\">Talla:</td>";
	$resultado.="<td><input name=\"talla\" type=\"text\" class=\"textbox\" id=\"talla\" size=\"10\" value=\"$talla\"></td>";
	$resultado.="<td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td colspan=\"2\" class=\"head\"><div align=\"center\">Aspecto General del Paciente</div></td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td><textarea name=\"aspecto\" class=\"textbox\" id=\"aspecto\" >$aspecto</textarea></td>";
	$resultado.="<td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\"> </td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"660\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">RX Torax ? </td>";
	$resultado.="<td><input name=\"rxtorax\" type=\"radio\" value=\"1\" onClick=\"Subirrxtorax(); ValorRxS();\">";
	$resultado.="Si";
	$resultado.="<input name=\"rxtorax\" type=\"radio\" value=\"0\" checked onClick=\"Ocultarxtorax();ValorRxN();\" >";
	$resultado.="No";
	$resultado.="<div id=\"rx\"><input name=\"hrxtorax\" type=\"hidden\" id=\"hrxtorax\" value=\"0\"></div></td>";
	$resultado.="<td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<div id=\"rayosx\">";
	$resultado.="</div>";
	$resultado.="<table width=\"660\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">ECG ? </td>";
	$resultado.="<td><input name=\"ecg\" type=\"radio\" value=\"1\"  onClick=\"Subirecg(); ValorECGS();\">";
	$resultado.="Si";
	$resultado.="<input name=\"ecg\" type=\"radio\" value=\"0\" checked onClick=\"Ocultarecg(); ValorECGN();\">";
	$resultado.="No";
	$resultado.="<div id=\"ecg\"><input name=\"hecg\" type=\"hidden\" id=\"hecg\"  value=\"0\"></div></td>";
	$resultado.="<td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" width=\"16\" height=\"16\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<div id=\"electro\">";
	$resultado.="</div>";
	$resultado.="<table width=\"660\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td><input type=\"submit\" name=\"Submit\" value=\"Enviar\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	echo $resultado;
?>