<?php
	$id="".$_POST['id']."";
	include '../../datos/datos.php';
	
	$datosm=Buscar_medicos($id);
	$id=$datos[0];
	$cedulam=$datos[1];
	$nombrem=$datos[2];
	$hestablecimiento=$datos[3];
	$establecimiento=$datos[4];
	$edad=$datos[5];
	$sexo=$datos[6];
	$dreccion=$datos[7];
	$telefono=$datos[8];
	$correo=$datos[9];
	$hlocalidad=$datos[10];
	$datosp=Buscar_pacientes($id);
	$id=$datos[0];
	$cedula=$datos[1];
	$nombre=$datos[2];
	$edad=$datos[3];
	$sexo=$datos[4];
	$telefono=$datos[5];
	$direccion=$datos[6];
	$hlocalidad=$datos[7];
	$correo=$datos[8];
	$resultado.="<form id=\"formulario\" name=\"formulario\">";
	$resultado.="<table class=\"tabla_form\" width=\"700\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\" width=\"67\">Fecha:</td>";
	$resultado.="<td  width=\"233\"><input name=\"fecha\" type=\"text\" id=\"fecha\" disabled class=\"textbox\" ></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Fecha')\"></td>";
	$resultado.="<td class=\"head\" width=\"88\">Numero:</td>";
	$resultado.="<td  width=\"158\"><input name=\"numero\"  type=\"text\" id=\"numero\" disabled class=\"textbox\" ></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Numero')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"700\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\" width=\"113\">Cedula del Paciente : </td>";
	$resultado.="<td   width=\"97\"><input id=\"idpaciente\" type=\"hidden\" class=\"textbox\" ><input name=\"cedula\" type=\"text\" id=\"cedulap\"  class=\"textbox\" size=\"15\" maxlength=\"15\" onChange=\"paciente(); diagex(); medico(); botones()\"></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Cedulap')\"></td>";
	$resultado.="<td class=\"head\" width=\"116\">Nombre y Apellido:</td>";
	$resultado.="<td  width=\"306\"><input name=\"nombrep\" type=\"text\" id=\"nombrep\" size=\"50\" maxlength=\"50\" disabled class=\"textbox\" ></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Nombrep')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"700\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">Edad:</td>";
	$resultado.="<td><input name=\"edad\"  type=\"text\" id=\"edad\" size=\"5\" maxlength=\"5\" disabled class=\"textbox\" ></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Edad')\"></td>";
	$resultado.="<td  class=\"head\">Sexo:</td>";
	$resultado.="<td><select name=\"sexo\" id=\"sexo\" disabled class=\"textbox\" >";
	$resultado.="<option value=\"M\">M</option>";
	$resultado.="<option value=\"F\">F</option>";
	$resultado.="</select></td><td><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Sexo')\"></td>";
	$resultado.="<td class=\"head\" width=\"66\">Telefono:</td>";
	$resultado.="<td  width=\"97\"><input name=\"telefono\"  class=\"textbox\" type=\"text\" id=\"telefono\" size=\"15\" maxlength=\"15\" disabled></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Telefono')\"></td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\" width=\"64\">email:</td>";
	$resultado.="<td  width=\"215\"><input name=\"email\"  class=\"textbox\" type=\"text\" id=\"email\" size=\"30\" maxlength=\"30\" disabled></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Email')\"></td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\" colspan=\"8\">Direcci&oacute;n del Paciente </td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td  colspan=\"8\"><textarea name=\"direccion\"  class=\"textbox\" cols=\"80\" rows=\"2\" id=\"direccion\" disabled></textarea></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Direccion')\"></td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td colspan=\"8\"><input type=\"hidden\" name=\"hubicacion\" id=\"hubicacion\"><input type=\"button\" name=\"Submit\" value=\"Ubicacion\" disabled>";
	$resultado.="<input type=\"button\" name=\"Submit2\" value=\"Editar\" onClick=\"editarPacientes(document.formulario.idpaciente.value,document.formulario.cedulap.value,document.formulario.nombrep.value,document.formulario.edad.value,document.formulario.sexo.value,document.formulario.telefono.value,document.formulario.email.value,document.formulario.direccion.value,document.formulario.hubicacion.value)\" disabled></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"700\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\" colspan=\"2\">Diagnostico</td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td><textarea name=\"diagnostico\"  class=\"textbox\" cols=\"100\" rows=\"2\" id=\"diagnostico\" disabled></textarea></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Diagnostico')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"700\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\" colspan=\"2\">Examen F&iacute;sico </td>";
	$resultado.="</tr>";
	$resultado.="<tr>";
	$resultado.="<td><textarea name=\"examen\"  class=\"textbox\" cols=\"100\" rows=\"2\" id=\"examen\" disabled></textarea><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Examen')\"></td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"700\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\">";
	$resultado.="Cedula del Medico :";
	$resultado.="</td>";
	$resultado.="<td>";
	$resultado.="<input id=\"idmedico\" type=\"hidden\">";
	$resultado.="<input name=\"cedulam\" type=\"text\"  class=\"textbox\" id=\"cedulam\" size=\"15\" maxlength=\"15\" disabled>";
	$resultado.="</td>";
	$resultado.="<td class=\"ayuda\">";
	$resultado.="<img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Cedulam')\">";
	$resultado.="</td>";
	$resultado.="<td class=\"head\">";
	$resultado.="Nombre y Apellido:";
	$resultado.="</td>";
	$resultado.="<td  width=\"306\">";
	$resultado.="<input name=\"nombrem\" type=\"text\"  class=\"textbox\" id=\"nombrem\" size=\"50\" maxlength=\"50\" disabled>";
	$resultado.="</td>";
	$resultado.="<td class=\"ayuda\">";
	$resultado.="<img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Nombrem')\">";
	$resultado.="</td>";
	$resultado.="</tr>";
	$resultado.="</table>";
	$resultado.="<table width=\"700\" border=\"1\">";
	$resultado.="<tr>";
	$resultado.="<td class=\"head\" >Establecimiento:</td>";
	$resultado.="<td><select name=\"establecimiento\"  class=\"textbox\" id=\"establecimiento\" disabled></select></td><td class=\"ayuda\"><img src=\"../../Imagenes/info.gif\" alt=\"Ayuda\" onmouseover=\"muestraAyuda(event, 'Establecimiento')\">";
	$resultado.="</td>";
	$resultado.="<td>";
	$resultado.="<input type=\"button\" name=\"med\" value=\"Editar\" disabled>";
	$resultado.="</td></tr>";
	$resultado.="</table>";
	$resultado.="<table><tr><td><input type=\"button\" name=\"guardar\" value=\"Agregar\" disabled>";
	$resultado.="<input type=\"button\" name=\"consultar\" value=\"Consulta\" onClick=\"consulta()\">";
	$resultado.="</td></tr></table>";
	$resultado.="</form>";
	return $resultado;
?>